 # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYWeChat' do

    pod 'TLTabBarController', :git => 'https://github.com/tbl00c/TLTabBarController.git', :tag => '0.0.6'
    pod 'TLKit', :git => 'https://github.com/tbl00c/TLKit.git', :tag => '0.0.21'
    pod 'ZZFLEX', :git => 'https://github.com/tbl00c/ZZFLEX.git', :tag => '0.2.0'


    
    
    pod 'Masonry', '~> 1.1.0'
    pod 'Reveal-SDK', '~> 2', :configurations => ['Debug']
    pod 'FMDB', '~> 2.7.2'
    pod 'CocoaLumberjack', '~> 3.3.0'
    pod 'UMengAnalytics', '~> 4.2.4'

end
